version: '3.5'
services:
    web:
        container_name: php
        # image: mtakashimori/php7.2-apache
        build:
            target: os
            context: .
        working_dir: /var/www/html/app
        volumes:
            - .:/var/www/html/app
        entrypoint:  [
            "/bin/sh",
            "/var/www/html/app/entrypoint.sh"
        ]    
        environment:
          - PHP_SHORT_OPEN_TAG=On
          - PHP_ERROR_REPORTING=E_ALL
          - PHP_DISPLAY_ERRORS=On
          - PHP_HTML_ERRORS=On            
        tty: true
        ports:
          - "8000:80"
        networks:
            main:
                aliases:
                    - web
networks:
    main:                      